
export const citiesSuggestions = [
    'Brasília',
    'Águas Claras',
    'Ceilândia',
    'Samambaia',
    'Taguatinga',
    'Planaltina',
    'Gama',
    'Sobradinho',
    'Santa Maria',
    'São Sebastião',
    'Recanto das Emas',
    'Riacho Fundo',
    'Vicente Pires',
    'Lago Sul',
    'Lago Norte'
]


export const neighborhoodsSuggestions = [
    'Águas Claras',
    'Asa Norte',
    'Asa Sul',
    'Sudoeste',
    'Noroeste',
    'Octogonal',
    'Cruzeiro',
    'Guará',
    'SIG',
    'SIA',
    'SCIA',
    'Taguatinga Norte',
    'Taguatinga Sul',
    'Taguatinga Centro',
    'Ceilândia Norte',
    'Ceilândia Sul',
    'Ceilândia Centro',
    'Samambaia Norte',
    'Samambaia Sul',
    'Sol Nascente',
    'Arniqueira',
    'Park Way',
    'Setor de Mansões',
    'Lago Sul',
    'Lago Norte',
    'Jardim Botânico',
    'Vicente Pires',
    'Riacho Fundo I',
    'Riacho Fundo II',
    'Recanto das Emas',
    'Setor Norte Gama',
    'Setor Sul Gama',
    'Setor Central Gama',
    'Setor Leste Gama',
    'Setor Oeste Gama',
    'Santa Maria',
    'Gama',
    'Planaltina',
    'Sobradinho',
    'Sobradinho II',
    'São Sebastião',
    'Paranoá',
    'Itapoã',
    'Estrutural',
    'SMPW',
    'Candangolândia',
    'Núcleo Bandeirante',
    'Park Sul',
    'Setor Industrial'
]
